### ISSUE TITLE
应用管理里看不到JavaCQ SDK Tool

### ISSUE THREAD

**Issue by Aruelius** [TaihouKai/QQCompiler#1]
![image](https://user-images.githubusercontent.com/25380989/52638822-c0f6f080-2f0d-11e9-893a-5d0a47765ff8.png)

**Comment by TaihouKai** [comment]
您好，我刚刚测试了一下（我用酷Q Air测试的，我Pro到期了没续费）

![image](https://user-images.githubusercontent.com/19760299/52656271-f8d94600-2ec3-11e9-839c-89fea06503e6.png)

我这里是可以看到的

请打开

![image](https://user-images.githubusercontent.com/19760299/52656311-10b0ca00-2ec4-11e9-9ded-8d74ee344574.png)

这个目录看下是不是有这个文件夹，以及这个文件夹里是不是有

![image](https://user-images.githubusercontent.com/19760299/52656383-3d64e180-2ec4-11e9-8de2-23c5a2bb7a34.png)

这些文件夹，并且都有内容

**Comment by Aruelius** [comment]
app文件夹里有com.sobte.cqp.jcq
![image](https://user-images.githubusercontent.com/25380989/52689626-bbdd8400-2f95-11e9-8086-b45805990cfc.png)
com.sobte.cqp.jcq文件夹里有
![image](https://user-images.githubusercontent.com/25380989/52689656-d3b50800-2f95-11e9-83ca-8f281f05153d.png)
但是应用管理还是看不到
![image](https://user-images.githubusercontent.com/25380989/52689685-f3e4c700-2f95-11e9-976f-ac3d2f19cd85.png)

**Comment by Aruelius** [comment]
我还顺便下了个Air，也是看不到插件= =
![image](https://user-images.githubusercontent.com/25380989/52689874-b6346e00-2f96-11e9-8aec-31165e9c9da5.png)

**Comment by TaihouKai** [comment]
> 我还顺便下了个Air，也是看不到插件= =
> ![image](https://user-images.githubusercontent.com/25380989/52689874-b6346e00-2f96-11e9-8aec-31165e9c9da5.png)

emmmmm，这个Air文件夹打包发给我一下我试试？

**Comment by Aruelius** [comment]
OK你看看，如果要Pro的话我把密钥打包给你。
下载地址：https://1i1.tw/Air.zip

**Comment by TaihouKai** [comment]
> OK你看看，如果要Pro的话我把密钥打包给你。
> 下载地址：https://1i1.tw/Air.zip

啊！我发现问题了，我漏放了一个文件，非常抱歉……m( _ _ )m

已经上传，文件名是com.sobte.cqp.jcq.cpk，放在根目录/app目录下

![image](https://user-images.githubusercontent.com/19760299/52706444-726c4500-2f53-11e9-98f1-9380909fd9d4.png)

像这样

**Comment by Aruelius** [comment]
OK,我就觉得少了个cpk文件 = =，现在可以用了，就是如图
![image](https://user-images.githubusercontent.com/25380989/52709623-4212be00-2fc8-11e9-8624-77567791960a.png)
回复会多一个换行，强迫症看着很不爽，自己能修改回复的格式嘛？

**Comment by TaihouKai** [comment]
> OK,我就觉得少了个cpk文件 = =，现在可以用了，就是如图
> ![image](https://user-images.githubusercontent.com/25380989/52709623-4212be00-2fc8-11e9-8624-77567791960a.png)
> 回复会多一个换行，强迫症看着很不爽，自己能修改回复的格式嘛？

src/com目录下有源代码，改了之后输出成jar包，然后替换app文件夹下的原jar就行了

不过我的源码写的乱七八糟的……抽空我去整理一下吧……（主要是没准备好有人想改的需求）

**Comment by Aruelius** [comment]
是这儿改吗，找不到输出换行的\n
![image](https://user-images.githubusercontent.com/25380989/52710748-10e7bd00-2fcb-11e9-845b-257821064a34.png)

我觉得目前只要改俩就行了 一个是最后换行去掉，然后python支持中文就完美了，不支持中文对我这种喜欢写中文的就感觉被限制了= =，发现运行不了只能把中文修改成英文。

**Comment by TaihouKai** [comment]
> 是这儿改吗，找不到输出换行的\n
> ![image](https://user-images.githubusercontent.com/25380989/52710748-10e7bd00-2fcb-11e9-845b-257821064a34.png)
> 
> 我觉得目前只要改俩就行了 一个是最后换行去掉，然后python支持中文就完美了，不支持中文对我这种喜欢写中文的就感觉被限制了= =，发现运行不了只能把中文修改成英文。

嗯，应该是这里，你可以试试。

Python的话理论上如果你直接在命令行里测试的话是可以输出中文的，不过通过这个东西到QQ里之后就奇妙地不行……我也懒得修bug了……

**Comment by Aruelius** [comment]
但是最奇怪的是，能输出中文。。。
![image](https://user-images.githubusercontent.com/25380989/52711241-4a6cf800-2fcc-11e9-8450-f872959becef.png)

**Comment by TaihouKai** [comment]
> 但是最奇怪的是，能输出中文。。。
> ![image](https://user-images.githubusercontent.com/25380989/52711241-4a6cf800-2fcc-11e9-8450-f872959becef.png)

根据我的推测，问题出在这里：

![image](https://user-images.githubusercontent.com/19760299/52711569-22e04600-2f60-11e9-8518-0529cd89e0ab.png)

八成是这个流传输的编码出问题了……但是我是真不知道咋修

**Comment by Aruelius** [comment]
这就到了知识盲区了

**Comment by Aruelius** [comment]
只能知道应该是命令传入的问题，输出是没有问题的

**Comment by TaihouKai** [comment]
你可以试试通过其他的办法来将system.out.print的内容获取出来

**Comment by TaihouKai** [comment]
> 只能知道应该是命令传入的问题，输出是没有问题的

你可以通过试试其他办法把内容传输进来……

**Comment by Aruelius** [comment]
OK谢谢！

**Comment by Aruelius** [comment]
发现了不能输出中文的原因：python对中文的特殊buff，只需要在`#p;`下面加上一行编码声明：`# -*- coding:gbk -*-`，下面继续输入python代码就行了。其实早就觉得是这个问题了，不过那时候给声明了utf-8，没用= =
![image](https://user-images.githubusercontent.com/25380989/52911544-3b45bd00-32e0-11e9-9a92-7e4cd3817f10.png)

**Comment by TaihouKai** [comment]
> 发现了不能输出中文的原因：python对中文的特殊buff，只需要在`#p;`下面加上一行编码声明：`# -*- coding:gbk -*-`，下面继续输入python代码就行了。其实早就觉得是这个问题了，不过那时候给声明了utf-8，没用= =
> ![image](https://user-images.githubusercontent.com/25380989/52911544-3b45bd00-32e0-11e9-9a92-7e4cd3817f10.png)

那我抽空把这行弄到源代码里

**Comment by Aruelius** [comment]
> > 发现了不能输出中文的原因：python对中文的特殊buff，只需要在`#p;`下面加上一行编码声明：`# -*- coding:gbk -*-`，下面继续输入python代码就行了。其实早就觉得是这个问题了，不过那时候给声明了utf-8，没用= =
> > ![image](https://user-images.githubusercontent.com/25380989/52911544-3b45bd00-32e0-11e9-9a92-7e4cd3817f10.png)
> 
> 那我抽空把这行弄到源代码里

OK

**Comment by Aruelius** [comment]
另外我好像知道为什么输出会多个换行了：
![image](https://user-images.githubusercontent.com/25380989/52912256-e8710300-32e9-11e9-8b76-e19bbed1f1c4.png)
CMD运行命令之后，最后一行都是空的，插件应该把这空行也输出出来了。

**Comment by TaihouKai** [comment]
> 另外我好像知道为什么输出会多个换行了：
> ![image](https://user-images.githubusercontent.com/25380989/52912256-e8710300-32e9-11e9-8b76-e19bbed1f1c4.png)
> CMD运行命令之后，最后一行都是空的，插件应该把这空行也输出出来了。

草，等我有空把末尾的换行符删了……
